### ISSUE TITLE
Support /youtube/v3/videoCategories endpoint

### ISSUE THREAD

**Issue by KieranP** [claudiob/yt#115]
Reference: https://developers.google.com/youtube/v3/docs/videoCategories/list

Needed to display a list of available video categories in order to upload a video with a category_id.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
