### ISSUE TITLE
Is there a way to set maxResults for channel.videos response?

### ISSUE THREAD

**Issue by mattruzicka** [claudiob/yt#157]
Some channels return hundreds of videos. It would be nice to be able to set the maxResults parameter for a channel's videos response.

I tried looking at the code and docs, but I'm not seeing a way to set maxResults. If anything, it looks like maxResults might default to 50, but hasn't been the case for me.

Unless it's already implemented, I'd be happy to try and implement a method of passing the max_results as an option, unless there's some reason it's not supported.

**Comment by claudiofullscreen** [comment]
Hello @mattruzicka – can you provide an example of what you’re trying to accomplish? 

Do you need to retrieve _all_ videos of a channel and you are only getting some?

Or you only want to fetch the first N and you are getting too many?

Thanks!

**Comment by mattruzicka** [comment]
@claudiofullscreen  I want to fetch the first N and I'm getting too many. 

Currently, I'm doing something like this: 

```
  channel = Yt::Channel.new id: channel_id
  channel.videos
  channel.videos.count => 300
```

But I want to only get 20 videos. I'm not sure how to set the maxResults parameter.

Am I thinking about this wrong? Does Yt make separate requests to get all the videos when I do "channel.videos.count"? Do I simply need to iterate over the first X videos that I need and that's it? Or will doing that still make a request to get all 300 videos.

Thanks.

**Comment by stavro** [comment]
Hi @mattruzicka, Please see the following snippet:

``` ruby
channel = Yt::Channel.new id: channel_id
channel.videos.first(10).count #=> 10
```

> Do I simply need to iterate over the first X videos that I need and that's it? Or will doing that still make a request to get all 300 videos.

The former.... `Yt` requests additional pages as needed. So if you iterate through to the 10th item, only one API request will have been made.

EDIT: Removed 2nd incorrect snippet. :oops:

**Comment by claudiofullscreen** [comment]
@mattruzicka 

Whenever a request is made to YouTube API, even if you only get a _page_ of results (for instance, the first 50 videos of the channel), the JSON response also contains a field called `"totalResults"` which reports how many items **in total** you would get, going through all the pages.

Therefore, when you call ~~`channel.videos.count`~~ `channel.videos.size`, you are only making **one** request which:
- reads `totalResults` telling you how many videos _in total_ you might possibly get
- fetches the first 50 videos (one page of results)

If you only iterate through the first 20 videos, then no extra call is made, so you are good to go.

The reason why, by default, I fetch 50 videos per page is that fetching 50 videos consumes the same YouTube API quota than fetching 20… but loads more data in less requests :scissors:.

But don't worry… that's the only call that is made.

If you want to make sure that is the case, just type this before you run your iteration:

``` ruby
Yt.configure do |config|
  config.log_level = :devel
end
```

This will give you a verbose log where you will see **every** request made to YouTube.
Remember… don't put this in production :grin: it's just for developing

**Comment by claudiofullscreen** [comment]
@mattruzicka

To be clear, I made a mistake in the comment above.

The way to get the number of total videos in one call is to type:

``` ruby
channel.videos.size
```

This is the command that will just make **one** request, fetching the first 50 videos and the `totalResults` counter.

---

If you call `channel.videos.count`, instead, you are actually **iterating through all the pages**. 
The reason why this method exists is that the `"totalResults"` values returned by YouTube API is **known to be only an estimation** which does not always perfectly match the actual number of results.

For instance, if you have deleted or private videos, sometimes they are still accounted for in the `"totalResults"` number, although you won't get them in your list.

---

In your specific case, since you don't really need any counter, I just invite you to go with what @stavro suggested… iterate through `channel.videos` and then just break the loop after 20 items. This will guarantee than you only make one request.

**Comment by mattruzicka** [comment]
Awesome. Thanks @claudiofullscreen and @stavro
