### ISSUE TITLE
[Add documentation about] Can only create playlists for default 'channel'

### ISSUE THREAD

**Issue by subimage** [claudiob/yt#161]
I'm giving playlists a full workout here...

I know that you can call `yt_account.create_playlist` and it will be created on the default channel. I also know that we can access all the channels that belong to an account.

My question is, why can't we create playlists for other channels that belong to the account?

Also, I believe the documentation here needs some work:  http://fullscreen.github.io/yt/playlists.html

Specifically, I go there looking to figure out how to `create_playlist`, but of course it's over in Account

**Comment by claudiofullscreen** [comment]
@subimage What do you mean by "we can access all the channels that belong to an account"?

I'm not sure I follow. When I log in to YouTube, I only have one channel.

**Comment by stavro** [comment]
@claudiofullscreen  One set of auth credentials can have multiple YouTube channels.

Check this out when logged into YouTube: https://www.youtube.com/channel_switcher?next=%2Faccount&feature=settings

**Comment by claudiofullscreen** [comment]
For YouTube, each channel that you can manage corresponds to a different account.

I understand the confusion: you are logged in with a single email and you **have access** to different channels. 

But what that page does is: let you **switch** from an account to another. At any given time you are always using YouTube as a **single** account (with a single default channel).

In terms of API, each Account has different credentials (access/refresh token), and different email, first name, last name. That is because each Account corresponds to a different **Google Plus** account.

You can verify this on your own: try to authenticate with `yt` using one of your "alternative" accounts and providing the `userinfo.email` scope, so you can call `account.email` or [other Yt::Account methods](http://fullscreen.github.io/yt/accounts.html). You will see that the email is not your main email but something like `"...@pages.plusgoogle.com"`.

**Comment by claudiofullscreen** [comment]
> Specifically, I go there looking to figure out how to create_playlist, but of course it's over in Account

Regarding this, you are right, the first paragraph of [this page](http://fullscreen.github.io/yt/playlists.html) could be re-written to explain that there's other ways to obtain an `Yt::Playlist` object, such as `channel.playlists.first` or `account.create_playlist`.

If you'd like to give it a try and send a PR against the `gh-pages` branch go for it.
