### ISSUE TITLE
Get comments

### ISSUE THREAD

**Issue by giannileggio** [claudiob/yt#171]
Comments can only be accessed by authenticated users

y = Yt::Video.new id: 'RC5DqWXZbRg'
y.comments
NoMethodError: undefined method `owner_name' for nil:NilClass
from gems/yt-0.22.0/lib/yt/models/video.rb:572:in`block in reports_params'

But looking at Youtube documentation, comments should be publicly accessible ie:
https://www.googleapis.com/youtube/v3/commentThreads?part=id,snippet,replies&textFormat=plainText&maxResults=100&videoId=U55NGD9Jm7M&key=

Documentation https://developers.google.com/youtube/v3/docs/commentThreads

Can we make an update to the gem? I can help

**Comment by claudiofullscreen** [comment]
@giannileggio The Yt gem does not support comments and comment threads yet.
They have only be added to the API a month ago and I didn't have time to implement them.

I'm happy to accept pull requests! Looks like [somebody else](https://github.com/Fullscreen/yt/compare/master...lamdan:master) has been working on this too.

The method you are referring to is described [here](http://fullscreen.github.io/yt/videos.html#analytics) and documented [here](http://www.rubydoc.info/gems/yt/Yt/Models/Video#comments-instance_method) and returns the **number** of comments for the video.

Since it's a method of YouTube Analytics API, it requires either the youtube analytics scope or a content owner.

**Comment by giannileggio** [comment]
Thanks @claudiofullscreen I'll check it out. It looks like @lamdan is doing a good job
