### ISSUE TITLE
Missing closing </iframe> tag calling embed_html on video

### ISSUE THREAD

**Issue by drummerroma** [claudiob/yt#172]
video = Yt::Video.new id:  'BPNYv0vd78A'
video.embed_html

```
<iframe type='text/html' src='http://www.youtube.com/embed/BPNYv0vd78A' width='640' height='360' frameborder='0' allowfullscreen='true'/>
```

I don't know if this behaviour depends on your gem.

**Comment by claudiofullscreen** [comment]
@drummerroma 

The HTML code is exactly what YouTube gives back. 
Since there is a closing slash at the end of the tag, I think YouTube considers "IFRAME" to be a self-closing tag, just like `<br />`.
I'm not sure whether this is supported by every browser, but that's the same result you would get by querying the YouTube API by yourself.
