### ISSUE TITLE
'options must be a hash' error on account

### ISSUE THREAD

**Issue by ermacaz** [claudiob/yt#182]
Hi,

I am trying to migrate an app using youtube_it to Yt.   I have the following code

```
 def configure_youtube(access_token, refresh_token)
        Yt.configure do |config|
          config.client_id = ENV["google_client_id"]
          config.client_secret = ENV["google_client_secret"]
        end
      client =  Yt::Account.new access_token: access_token, refresh_token: refresh_token
      email = client.email
 end
```

When  I call client.email or any account attribute (id, name, etc) I get the error 'options must be a hash'.  Full stack trace here: https://gist.github.com/ermacaz/662b6345a69a4e274dd1

If I call client.videos I get back an instance of Yt::Collections::Videos, but calling anything like client.videos.first also returns 'options must be a hash'.

Any help is appreciated

**Comment by claudiofullscreen** [comment]
Hello @ermacaz and thanks for stopping by!

Looks like this is the same issue discussed in #165 – I closed that PR because, in that case, @MaximSt was overriding the expected behavior of Ruby's JSON library with a gem.

Can you tell me if that's the case in your app too? 

And can you also try to temporarily edit your local file `/home/ermacaz/.rvm/gems/ruby-2.2.1@Nfuse/gems/yt-0.23.2/lib/yt/request.rb` as suggested here? https://github.com/Fullscreen/yt/pull/165/files

(Remember to run `gem pristine yt` if you want to cancel the change)

I'd like to understand if different JSON libraries behave in different ways before deciding how to proceed. Thanks

**Comment by ermacaz** [comment]
Hi,

Thanks for getting back to me.  I also have the oj_mimic_json gem and it is
causing the problems.  I tried the edit in the pending pull request you
sent and it worked perfectly.  Do you plan on merging it to the gem?

On Wed, May 20, 2015 at 3:13 PM, claudiofullscreen <notifications@github.com

**Comment by claudiofullscreen** [comment]
Hello @ermacaz – looks like @MaximSt already did what I was about to do, that is, open an issue for oj: https://github.com/ohler55/oj/issues/238

Since @ohler55 (developer of oj) said he's working on it, I'd wait to see the results.

**Comment by ermacaz** [comment]
Sounds good. Thank you for the help

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
