### ISSUE TITLE
Uploading video to app owner's youtube account.

### ISSUE THREAD

**Issue by petkokaravelov** [claudiob/yt#185]
Hi I have used yt gem and I figured out that videos are uploaded to oAuth2 authenticated user's youtube account.
But I want to know if there is a way to upload video to registered app owner's youtube account not logged in user's youtube account.
Please let me know if there is a way to do that.
Thanks.
Petko.

**Comment by pentagon** [comment]
Any suggestion on this?

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
