### ISSUE TITLE
Feature Request: Location Latitude & Longitude

### ISSUE THREAD

**Issue by jayhuber** [claudiob/yt#188]
Maybe I missed it, but would love to be able to read, and upload with latitude and longitude.

Google API:
recordingDetails.location   object - The geolocation information associated with the video.
recordingDetails.location.latitude - double - Latitude in degrees.
recordingDetails.location.longitude - double - Longitude in degrees.

**Comment by claudiofullscreen** [comment]
You are right, it's not there. I'll take a look!

**Comment by jayhuber** [comment]
Thanks!  Gem is awesome.  I was using youtube_it, but Google deprecated a few of the calls yesterday about 2pm CST.  

The Gem saved me in a bind.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.

**Comment by kangkyu** [comment]
related, https://github.com/Fullscreen/yt/pull/252
