### ISSUE TITLE
Sorting by latest but only including public videos

### ISSUE THREAD

**Issue by claudeomusic** [claudiob/yt#199]
Hi! Really great gem!

I was wondering if there might be a more efficient way to get the latest videos uploaded by a user but excluding unlisted/non-public videos? The only way I could think of accomplishing this is like this but it's extremely inefficient:

```
account = Yt::Account.new access_token: youtube_access_token
account.videos.where(order: 'date').map.to_a.select{|video| video.public?}
```

 Appreciate your help!

Thanks

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
