### ISSUE TITLE
Where params aren't respected if params should have 0 results

### ISSUE THREAD

**Issue by trevorturk** [claudiob/yt#214]
For example, I expect to get 0 results here:

```
Yt::Account.new(access_token: token).playlists.where(title: "invalid").first.title
=> "Favorites"
```

**Comment by mdurn** [comment]
May or may not be related, but I am also having an issue where the params for the video search don't seem to be respected.

This example works as expected:

``` ruby
videos = Yt::Collections::Videos.new
videos.where(order: 'relevance', q: "The Phenomenauts", video_category_id: 10, max_results: 3).first
videos
```

I get three `@items` in the list which is what I expect.

This example leads to issues:

``` ruby
videos = Yt::Collections::Videos.new
videos.where(order: 'relevance', q: "The Phenomenots", video_category_id: 10, max_results: 3).first
videos
```

There are zero `@items` in the list. However, doing `videos.count` or `videos.each` ends up timing out since it retrieves videos with seemingly no limit.

Maybe I'm misunderstanding something here, but the result was unexpected. Thanks in advance for any help (also hi Claudio!).

**Comment by claudiofullscreen** [comment]
Haha, hi @mdurn ! Long time no see :grinning:

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
