### ISSUE TITLE
Channel not found error

### ISSUE THREAD

**Issue by naz** [claudiob/yt#215]
Hi guys. Was just wandering if there is any convenient way to check if the channel exists. As at the moment the only thing that can be done is doing something like this 

``` ruby
Yt::Channel.new(id: channel_id).title
```

Which throws `Yt::Errors::NoItems` and is quite ambiguous. After reading youtube api docs it looks like they have just that mehod [here](https://developers.google.com/youtube/v3/docs/errors#channels) and they return 404 with `channelNotFound`.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
