### ISSUE TITLE
Videos: list vs search

### ISSUE THREAD

**Issue by karianne** [claudiob/yt#229]
In `Collections::Videos`, i find this code:

```
      # YouTube API provides two different endpoints to get a list of videos:
      # /videos should be used when the query specifies video IDs or a chart,
      # /search otherwise.
      # @return [Boolean] whether to use the /videos endpoint.
      # @todo: This is one of three places outside of base.rb where @where_params
      #   is accessed; it should be replaced with a filter on params instead.
      def use_list_endpoint?
        @where_params ||= {}
        @parent.nil? && (@where_params.keys & [:id, :chart]).any?
      end
```

Why should `/videos` only be used when the query specifies video IDs or a chart? My specific problem is that I want to load several videos in one go, but the /search endpoint is providing me with truncated descriptions, and I need the full descriptions. I know I can fetch one and one video, but that is both quota- and time consuming.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
