### ISSUE TITLE
Channel search

### ISSUE THREAD

**Issue by amalagaura** [claudiob/yt#237]
Youtube's search endpoint supports searching videos,channels and playlists.

https://developers.google.com/youtube/v3/docs/search

 In order to add this feature will you accept a pull request that does something similar to the where query code for videos where it selects the different endpoints? That should be all that is required to support the channel and playlist search.

**Comment by csroberson** [comment]
Did you ever get a response to this?

**Comment by amalagaura** [comment]
No I didn't. I didn't end up doing it either because we didn't get around to it. It is a small change in the channel file to make it the same as the video file. This method and related code https://github.com/Fullscreen/yt/blob/master/lib/yt/collections/videos.rb#L131 needs to be in the channels.rb to support channel search by passing it the query.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
