### ISSUE TITLE
preload status, snippet and content_details for a single video

### ISSUE THREAD

**Issue by masterkain** [claudiob/yt#238]
`video = Yt::Video.new(url: resource_url, includes: [:status, :snippet, :content_details])`

is that supported in some form to reduce the calls?

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
