### ISSUE TITLE
Can't fetch comments

### ISSUE THREAD

**Issue by ngw** [claudiob/yt#239]
Hi, sorry if I open an issue, there's no ML/discussion group and I had no luck until now on SO.

https://stackoverflow.com/questions/32201359/retrieving-youtube-comments-with-fullscreen-yt

This is probably due to the scope I'm requesting, can someone help me? TIA

**Comment by claudiofullscreen** [comment]
I'm not sure that scope is correct… sounds to me like an old YouTube API **V2** scope.

The API **V3** scopes all start with `https://www.googleapis.com/auth/`.

Since you are trying to access analytics data, I think the scope you need to ask for is `https://www.googleapis.com/auth/yt-analytics.readonly` as explained here: https://developers.google.com/youtube/analytics/guides/auth/server-side-web-apps

**Comment by ngw** [comment]
Well, AFAIK it appends the url to the scope.
The permission error is fixed, still can't fetch the comments: have you ever tried doing it? Appears to me that video.comments is just an alias to comments_count

```
video.comments
=> {:total=>5}
```

**Comment by ngw** [comment]
Apparently it can't be done

```
# with youtube_it
client = YouTubeIt::Client.new
client.comments(video_id)
# with yt: not supported (was removed from YouTube API V3)
```

**Comment by ngw** [comment]
(which is not true, you can retrieve comments with V3, and it would be very useful if you could write in the README whats's still missing from the gem)

**Comment by bodrovis** [comment]
@ngw https://github.com/Fullscreen/yt/pull/235

**Comment by claudiofullscreen** [comment]
Sorry @ngw there was a miscommunication.

As you can read in the guides http://fullscreen.github.io/yt/videos.html#analytics
the method `comments` in Yt fetches the analytics related to comments, not the comments themselves.

Up to a few months ago, the actual comments were not available in YouTube API V3.

Now they are available, and there is an open PR for that.

**Comment by ngw** [comment]
@claudiofullscreen is there en ETA for when we will be able to retrieve comments with the gem?

**Comment by claudiofullscreen** [comment]
Before accepting the PR, I need to check that it's working and add some tests for that.

I haven't had the time so far, but you can help by fetching the code from that PR and see if it works for you.

Simply, in your Gemfile, replace

``` ruby
gem 'yt'
```

with

``` ruby
gem 'yt', github: 'ezr-ondrej/yt'
```

then `bundle install` and you should have `video.comment_threads` available.
Let me know if it works!

**Comment by kostyakch** [comment]
Tell me please, how can I posting a comment to the video?

**Comment by webdz9r** [comment]
I was able to load comments. A video i'm using has 3526 comments but when Ioad the threads it only loads 736. Any reason for this or is there a param to pull "all" comments"

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
