### ISSUE TITLE
Don’t store `.where` conditions when `.where` is not used

### ISSUE THREAD

**Issue by claudiofullscreen** [claudiob/yt#44]
If you get a list with a `where` condition first:

```
channel.videos.where(q: 'anything').count
```

and then try to get the same list without any `where` condition:

```
channel.videos.count
```

you still get the first video count, because the cached list is returned.
This only happens if the second call _does not have any `where` condition_.
If a _different_ condition is specified, it does not happen.

**Comment by PurityLake** [comment]
Well isn't that how the behavior is specified?

Line 18 of `videos_spec.rb`

`it 'only applies the query on the first call'`

I believe as it has been specified that `where` is not mutative in nature perhaps an mutative implementation of `where` as `where!` may be a solution.

**Comment by kangkyu** [comment]
Thank you for using yt gem. We recently opened this "Issues" tab back. We are also working on the prioritization process, to maintain yt better. As a part of maintenance plan, we decided to close all issues from the past, because they might be stale and outdated. Please feel free to reopen if you think necessary.
